version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      SERVER_PORT: 9000
      JWT_SECRET: 1e3AQ4pPB8WJswNnQBNcl75bzj8lCx1U
      DATABASE_URI: mongodb://127.0.0.1:27017/easy-generators
      BACKEND_URL: http://localhost:9000
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_BACKEND_URL: http://localhost:9000
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
